Import libarary for projects

In [13]:
import pandas as pd
import numpy as np
import keras
from keras.models import Sequential
from keras.layers import Dense
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error
from math import sqrt

Download dataset using for projects

In [14]:
concrete_data = pd.read_csv('https://cocl.us/concrete_data')
concrete_data.head()

,Cement,Blast Furnace Slag,Fly Ash,Water,Superplasticizer,Coarse Aggregate,Fine Aggregate,Age,Strength
0,540.0,0.0,0.0,162.0,2.5,1040.0,676.0,28,79.99
1,540.0,0.0,0.0,162.0,2.5,1055.0,676.0,28,61.89
2,332.5,142.5,0.0,228.0,0.0,932.0,594.0,270,40.27
3,332.5,142.5,0.0,228.0,0.0,932.0,594.0,365,41.05
4,198.6,132.4,0.0,192.0,0.0,978.4,825.5,360,44.30

Drop some columns that is not essential and Get data for targets

In [15]:
targets=concrete_data['Strength'] # target to predict
predictors = concrete_data.drop(['Age','Strength'],axis=1) #skip columns that are not features
predictors.head() # display data to test

,Cement,Blast Furnace Slag,Fly Ash,Water,Superplasticizer,Coarse Aggregate,Fine Aggregate
0,540.0,0.0,0.0,162.0,2.5,1040.0,676.0
1,540.0,0.0,0.0,162.0,2.5,1055.0,676.0
2,332.5,142.5,0.0,228.0,0.0,932.0,594.0
3,332.5,142.5,0.0,228.0,0.0,932.0,594.0
4,198.6,132.4,0.0,192.0,0.0,978.4,825.5

<b> A. Build a baseline model </b>
(Hidden layers consist 10 nodes, loss is mean_squared_error, optimizer is adam)

Normalize data before going to process

In [16]:
predictors_norm = (predictors - predictors.mean()) / predictors.std()
predictors_norm.head()

,Cement,Blast Furnace Slag,Fly Ash,Water,Superplasticizer,Coarse Aggregate,Fine Aggregate
0,2.476712,-0.856472,-0.846733,-0.916319,-0.620147,0.862735,-1.217079
1,2.476712,-0.856472,-0.846733,-0.916319,-0.620147,1.055651,-1.217079
2,0.491187,0.795140,-0.846733,2.174405,-1.038638,-0.526262,-2.239829
3,0.491187,0.795140,-0.846733,2.174405,-1.038638,-0.526262,-2.239829
4,-0.790075,0.678079,-0.846733,0.488555,-1.038638,0.070492,0.647569

In [17]:
n_cols=predictors_norm.shape[1]
# define regression model
def regression_model():
    # create model
    model = Sequential()
    model.add(Dense(10, activation='relu', input_shape=(n_cols,)))
    model.add(Dense(1))
    
    # compile model
    model.compile(optimizer='adam', loss='mean_squared_error',metrics=["accuracy"])
    return model

In [18]:
# prepare model to train
model = regression_model()

1.Split data set into test and train datasets

In [19]:
x_train,x_test,y_train,y_test=train_test_split(predictors_norm, targets, test_size=0.3)# not indicate rand_state to make sure it is generated randomly

2.Traing model with epochs=100

In [20]:
# train the model with epochs=100
model.fit(x_train, y_train, epochs=100, verbose=2)

Epoch 1/100
 - 1s - loss: 1546.9331 - acc: 0.0000e+00
Epoch 2/100
 - 0s - loss: 1532.2939 - acc: 0.0000e+00
Epoch 3/100
 - 0s - loss: 1517.5348 - acc: 0.0000e+00
Epoch 4/100
 - 0s - loss: 1502.6488 - acc: 0.0000e+00
Epoch 5/100
 - 0s - loss: 1487.2568 - acc: 0.0000e+00
Epoch 6/100
 - 0s - loss: 1471.7070 - acc: 0.0000e+00
Epoch 7/100
 - 0s - loss: 1455.6110 - acc: 0.0000e+00
Epoch 8/100
 - 0s - loss: 1439.0004 - acc: 0.0000e+00
Epoch 9/100
 - 0s - loss: 1421.9406 - acc: 0.0000e+00
Epoch 10/100
 - 0s - loss: 1404.1110 - acc: 0.0000e+00
Epoch 11/100
 - 0s - loss: 1385.6128 - acc: 0.0000e+00
Epoch 12/100
 - 0s - loss: 1366.3004 - acc: 0.0000e+00
Epoch 13/100
 - 0s - loss: 1346.5178 - acc: 0.0000e+00
Epoch 14/100
 - 0s - loss: 1325.8064 - acc: 0.0000e+00
Epoch 15/100
 - 0s - loss: 1304.4520 - acc: 0.0000e+00
Epoch 16/100
 - 0s - loss: 1282.4766 - acc: 0.0000e+00
Epoch 17/100
 - 0s - loss: 1259.5844 - acc: 0.0000e+00
Epoch 18/100
 - 0s - loss: 1235.5905 - acc: 0.0000e+00
Epoch 19/100
 - 0s - loss: 1210.7395 - acc: 0.0000e+00
Epoch 20/100
 - 0s - loss: 1185.3689 - acc: 0.0000e+00
Epoch 21/100
 - 0s - loss: 1158.7389 - acc: 0.0000e+00
Epoch 22/100
 - 0s - loss: 1131.5681 - acc: 0.0000e+00
Epoch 23/100
 - 0s - loss: 1102.7150 - acc: 0.0000e+00
Epoch 24/100
 - 0s - loss: 1073.4835 - acc: 0.0000e+00
Epoch 25/100
 - 0s - loss: 1042.9351 - acc: 0.0000e+00
Epoch 26/100
 - 0s - loss: 1012.3703 - acc: 0.0000e+00
Epoch 27/100
 - 0s - loss: 980.4429 - acc: 0.0000e+00
Epoch 28/100
 - 0s - loss: 948.1250 - acc: 0.0000e+00
Epoch 29/100
 - 0s - loss: 915.1913 - acc: 0.0000e+00
Epoch 30/100
 - 0s - loss: 882.1886 - acc: 0.0000e+00
Epoch 31/100
 - 1s - loss: 848.7485 - acc: 0.0014
Epoch 32/100
 - 0s - loss: 815.9384 - acc: 0.0014
Epoch 33/100
 - 0s - loss: 782.5185 - acc: 0.0014
Epoch 34/100
 - 1s - loss: 749.3743 - acc: 0.0000e+00
Epoch 35/100
 - 0s - loss: 716.5842 - acc: 0.0000e+00
Epoch 36/100
 - 0s - loss: 684.4399 - acc: 0.0000e+00
Epoch 37/100
 - 0s - loss: 652.6282 - acc: 0.0000e+00
Epoch 38/100
 - 0s - loss: 622.3025 - acc: 0.0000e+00
Epoch 39/100
 - 0s - loss: 592.2008 - acc: 0.0014
Epoch 40/100
 - 0s - loss: 562.7972 - acc: 0.0000e+00
Epoch 41/100
 - 0s - loss: 534.5255 - acc: 0.0000e+00
Epoch 42/100
 - 0s - loss: 507.1873 - acc: 0.0000e+00
Epoch 43/100
 - 0s - loss: 481.4296 - acc: 0.0000e+00
Epoch 44/100
 - 0s - loss: 456.8706 - acc: 0.0000e+00
Epoch 45/100
 - 0s - loss: 433.8438 - acc: 0.0000e+00
Epoch 46/100
 - 0s - loss: 411.5074 - acc: 0.0014
Epoch 47/100
 - 0s - loss: 390.9542 - acc: 0.0028
Epoch 48/100
 - 0s - loss: 371.5330 - acc: 0.0028
Epoch 49/100
 - 0s - loss: 353.4157 - acc: 0.0028
Epoch 50/100
 - 0s - loss: 336.2622 - acc: 0.0014
Epoch 51/100
 - 0s - loss: 320.7402 - acc: 0.0014
Epoch 52/100
 - 1s - loss: 306.3545 - acc: 0.0014
Epoch 53/100
 - 0s - loss: 293.3199 - acc: 0.0000e+00
Epoch 54/100
 - 0s - loss: 281.8575 - acc: 0.0000e+00
Epoch 55/100
 - 0s - loss: 271.1581 - acc: 0.0000e+00
Epoch 56/100
 - 0s - loss: 261.8368 - acc: 0.0000e+00
Epoch 57/100
 - 0s - loss: 253.4929 - acc: 0.0000e+00
Epoch 58/100
 - 0s - loss: 245.9118 - acc: 0.0000e+00
Epoch 59/100
 - 0s - loss: 239.8013 - acc: 0.0000e+00
Epoch 60/100
 - 0s - loss: 233.5999 - acc: 0.0000e+00
Epoch 61/100
 - 0s - loss: 228.7078 - acc: 0.0000e+00
Epoch 62/100
 - 0s - loss: 224.1977 - acc: 0.0000e+00
Epoch 63/100
 - 0s - loss: 220.1128 - acc: 0.0000e+00
Epoch 64/100
 - 0s - loss: 216.5050 - acc: 0.0000e+00
Epoch 65/100
 - 0s - loss: 213.5204 - acc: 0.0000e+00
Epoch 66/100
 - 0s - loss: 210.5402 - acc: 0.0000e+00
Epoch 67/100
 - 0s - loss: 208.0949 - acc: 0.0000e+00
Epoch 68/100
 - 0s - loss: 205.8650 - acc: 0.0000e+00
Epoch 69/100
 - 0s - loss: 203.8011 - acc: 0.0000e+00
Epoch 70/100
 - 0s - loss: 201.9155 - acc: 0.0000e+00
Epoch 71/100
 - 0s - loss: 200.3871 - acc: 0.0000e+00
Epoch 72/100
 - 0s - loss: 198.9153 - acc: 0.0000e+00
Epoch 73/100
 - 0s - loss: 197.5046 - acc: 0.0000e+00
Epoch 74/100
 - 0s - loss: 196.1514 - acc: 0.0000e+00
Epoch 75/100
 - 0s - loss: 194.8599 - acc: 0.0000e+00
Epoch 76/100
 - 0s - loss: 193.6795 - acc: 0.0000e+00
Epoch 77/100
 - 0s - loss: 192.5539 - acc: 0.0000e+00
Epoch 78/100
 - 0s - loss: 191.5368 - acc: 0.0000e+00
Epoch 79/100
 - 0s - loss: 190.4860 - acc: 0.0000e+00
Epoch 80/100
 - 0s - loss: 189.4468 - acc: 0.0000e+00
Epoch 81/100
 - 0s - loss: 188.5151 - acc: 0.0000e+00
Epoch 82/100
 - 0s - loss: 187.5456 - acc: 0.0000e+00
Epoch 83/100
 - 0s - loss: 186.6775 - acc: 0.0000e+00
Epoch 84/100
 - 0s - loss: 185.8259 - acc: 0.0000e+00
Epoch 85/100
 - 0s - loss: 184.9700 - acc: 0.0000e+00
Epoch 86/100
 - 0s - loss: 184.1508 - acc: 0.0000e+00
Epoch 87/100
 - 0s - loss: 183.3387 - acc: 0.0000e+00
Epoch 88/100
 - 0s - loss: 182.6635 - acc: 0.0000e+00
Epoch 89/100
 - 0s - loss: 181.9228 - acc: 0.0000e+00
Epoch 90/100
 - 0s - loss: 181.1931 - acc: 0.0000e+00
Epoch 91/100
 - 0s - loss: 180.4460 - acc: 0.0000e+00
Epoch 92/100
 - 0s - loss: 179.7958 - acc: 0.0000e+00
Epoch 93/100
 - 0s - loss: 179.1006 - acc: 0.0000e+00
Epoch 94/100
 - 0s - loss: 178.4262 - acc: 0.0000e+00
Epoch 95/100
 - 0s - loss: 177.8410 - acc: 0.0000e+00
Epoch 96/100
 - 0s - loss: 177.1752 - acc: 0.0000e+00
Epoch 97/100
 - 0s - loss: 176.6639 - acc: 0.0000e+00
Epoch 98/100
 - 0s - loss: 176.1035 - acc: 0.0000e+00
Epoch 99/100
 - 0s - loss: 175.4057 - acc: 0.0000e+00
Epoch 100/100
 - 0s - loss: 174.9030 - acc: 0.0000e+00

3.Evaluate with data test

In [21]:
#evaluate on data test
scores=model.evaluate(x_test,y_test,verbose=0)
print('Accuracy is ',scores[1]*100)

# compute mean_squared_error
pred_test= model.predict(x_test)
print("Mse is:",np.sqrt(mean_squared_error(y_test,pred_test)))

Accuracy is  0.0
Mse is: 13.36668202109825

4. Repeat steps 1 - 3, 50 times

In [22]:
mse_list=[]
for x in range(50):
    #step 1
    x_train,x_test,y_train,y_test=train_test_split(predictors_norm, targets, test_size=0.3)
    
    #step 2
    print("Training step ",(x+1),"...")
    model.fit(x_train, y_train, epochs=100, verbose=0) # step 2
    
    #step 3:
    #evaluate on data test
    scores=model.evaluate(x_test,y_test,verbose=0)
    # compute mean_squared_error
    pred_test= model.predict(x_test)
    mse=np.sqrt(mean_squared_error(y_test,pred_test))   
    mse_list.append(mse)

Training step  1 ...
Training step  2 ...
Training step  3 ...
Training step  4 ...
Training step  5 ...
Training step  6 ...
Training step  7 ...
Training step  8 ...
Training step  9 ...
Training step  10 ...
Training step  11 ...
Training step  12 ...
Training step  13 ...
Training step  14 ...
Training step  15 ...
Training step  16 ...
Training step  17 ...
Training step  18 ...
Training step  19 ...
Training step  20 ...
Training step  21 ...
Training step  22 ...
Training step  23 ...
Training step  24 ...
Training step  25 ...
Training step  26 ...
Training step  27 ...
Training step  28 ...
Training step  29 ...
Training step  30 ...
Training step  31 ...
Training step  32 ...
Training step  33 ...
Training step  34 ...
Training step  35 ...
Training step  36 ...
Training step  37 ...
Training step  38 ...
Training step  39 ...
Training step  40 ...
Training step  41 ...
Training step  42 ...
Training step  43 ...
Training step  44 ...
Training step  45 ...
Training step  46 ...
Training step  47 ...
Training step  48 ...
Training step  49 ...
Training step  50 ...

5.Print the mean and the standard deviation of the mean squared errors.

In [24]:
print("Mean is %.2f%%  and STD is: (+/- %.2f%%)" % (np.mean(mse_list), np.std(mse_list)))

Mean is 11.58%  and STD is: (+/- 0.39%)